/** Durable research evaluation facts and their session projection. @module @deepseek-ai/dsh-research/health */
import { z } from 'zod'
import type { ProjectionDefinition } from '@deepseek-ai/dsh-session-projection'
import type { ResearchReportIr, VerifiedEvidenceLedger } from './types.ts'

/** Correctness invariants that must all hold for a healthy research publication. */
export interface ResearchCorrectness {
  readonly revisionPinned: boolean
  readonly provenanceComplete: boolean
  readonly criticalClaimsEvidence: boolean
  readonly scoringAxesSeparated: boolean
  readonly publishExactlyOnce: boolean
  readonly receiptConsistent: boolean
}

/** Deterministic health result for one completed research publication. */
export interface ResearchEvaluation {
  readonly reportHash: string
  readonly reportFamily: ResearchReportIr['family']
  readonly compilerVersion: VerifiedEvidenceLedger['compilerVersion']
  readonly healthy: boolean
  readonly correctness: ResearchCorrectness
  readonly evidenceCount: number
  readonly unknownCount: number
  readonly navigationFailureCount: number
  readonly collection: VerifiedEvidenceLedger['collection']
}

/** Application-owned publication facts used by deterministic health evaluation. */
export interface ResearchPublicationFacts {
  readonly reportHash: string
  readonly markdownPath: string
  readonly htmlPath: string
  readonly publishCount: number
}

/** Low-cardinality metric point derived without report or source text. */
export interface ResearchHealthMetric {
  readonly name:
    | 'dsh.research.healthy'
    | 'dsh.research.correctness_failures'
    | 'dsh.research.evidence'
    | 'dsh.research.unknown'
    | 'dsh.research.navigation_failures'
    | 'dsh.research.source_files'
    | 'dsh.research.source_bytes'
    | 'dsh.research.duration_ms'
    | 'dsh.research.cache_hit'
  readonly value: number
  readonly attributes: {
    readonly reportFamily: ResearchReportIr['family']
    readonly compilerVersion: VerifiedEvidenceLedger['compilerVersion']
  }
}

/** One efficiency axis computed only after the baseline sample floor is met. */
export interface ResearchEfficiencyAxis {
  readonly median: number
  readonly p95: number
  readonly mad: number
  readonly warnAbove: number
}

/** Statistical efficiency baseline for comparable research runs. */
export interface ResearchEfficiencyBaseline {
  readonly sampleCount: number
  readonly durationMs: ResearchEfficiencyAxis
  readonly sourceBytesRead: ResearchEfficiencyAxis
  readonly filesRead: ResearchEfficiencyAxis
}

/** Session read model for research validation, publication, and latest health. */
export interface ResearchHealthProjection {
  readonly prepareAttempts: number
  readonly invalidPrepareAttempts: number
  readonly publishCount: number
  readonly latestReceipt: Omit<ResearchPublicationFacts, 'publishCount'> | null
  readonly modelUsage: ResearchModelUsage
  readonly latest: ResearchEvaluation | null
}

/** Disjoint model token accounting accumulated from durable assistant messages. */
export interface ResearchModelUsage {
  readonly inputTokens: number
  readonly outputTokens: number
  readonly cacheReadTokens: number
  readonly cacheWriteTokens: number
  readonly reasoningTokens: number
}

declare module '@deepseek-ai/dsh-session/types' {
  interface SessionEventMap {
    /** Sealed evidence selected for subsequent Report IR validation in this session. */
    'research/evidence-collected': { ledger: VerifiedEvidenceLedger }
    /** One Report IR validation outcome; raw validation tokens are never durable. */
    'research/report-prepared': { status: 'invalid' | 'validated'; outputPath: string; reportHash?: string; diagnostics: string[] }
    /** One committed publication receipt generated by the application. */
    'research/report-published': { reportHash: string; markdownPath: string; htmlPath: string }
    /** Whole deterministic research health result for the completed publication. */
    'research/evaluation-completed': ResearchEvaluation
  }
}

declare module '@deepseek-ai/dsh-session-projection/types' {
  interface SessionProjectionMap {
    researchHealth: ResearchHealthProjection
  }
}

/**
 * Evaluate hard publication invariants from sealed inputs and the application receipt.
 * @param report - validated Report IR.
 * @param ledger - sealed evidence ledger.
 * @param publication - application-computed receipt and observed publish count.
 * @returns deterministic health result.
 */
export function evaluateResearchPublication(
  report: ResearchReportIr,
  ledger: VerifiedEvidenceLedger,
  publication: ResearchPublicationFacts,
): ResearchEvaluation {
  const revisionByRepository = new Map(
    ledger.repositories.map(item => [`${item.repository.owner}/${item.repository.name}`, item.revision.sha]),
  )
  const correctness: ResearchCorrectness = {
    revisionPinned: ledger.evidence.every(
      item => revisionByRepository.get(`${item.repository.owner}/${item.repository.name}`) === item.revision,
    ),
    provenanceComplete: ledger.evidence.every(
      item => item.revision.length > 0 && item.path.length > 0 && item.sourceUrl.length > 0 && item.excerpt.length > 0,
    ),
    criticalClaimsEvidence: report.claims.filter(claim => claim.critical).every(claim => claim.evidenceIds.length > 0),
    scoringAxesSeparated: report.candidates.every(
      candidate =>
        Number.isSafeInteger(candidate.stars) &&
        candidate.stars >= 0 &&
        Number.isFinite(candidate.topicMatch) &&
        candidate.topicMatch >= 0 &&
        candidate.topicMatch <= 100,
    ),
    publishExactlyOnce: publication.publishCount === 1,
    receiptConsistent:
      publication.reportHash.length === 64 &&
      publication.markdownPath.endsWith('.md') &&
      publication.htmlPath === `${publication.markdownPath.slice(0, -3)}.html`,
  }
  return {
    reportHash: publication.reportHash,
    reportFamily: report.family,
    compilerVersion: ledger.compilerVersion,
    healthy: Object.values(correctness).every(Boolean),
    correctness,
    evidenceCount: ledger.evidence.length,
    unknownCount: ledger.unknownCriteria.length,
    navigationFailureCount: ledger.navigation.filter(item => item.status !== 'used').length,
    collection: ledger.collection,
  }
}

/**
 * Derive low-cardinality health metrics from one sealed evaluation.
 * @param evaluation - deterministic publication health result.
 * @returns metric points without repository, report, or source content.
 */
export function researchHealthMetrics(evaluation: ResearchEvaluation): readonly ResearchHealthMetric[] {
  const attributes = { reportFamily: evaluation.reportFamily, compilerVersion: evaluation.compilerVersion }
  return [
    { name: 'dsh.research.healthy', value: evaluation.healthy ? 1 : 0, attributes },
    {
      name: 'dsh.research.correctness_failures',
      value: Object.values(evaluation.correctness).filter(value => !value).length,
      attributes,
    },
    { name: 'dsh.research.evidence', value: evaluation.evidenceCount, attributes },
    { name: 'dsh.research.unknown', value: evaluation.unknownCount, attributes },
    { name: 'dsh.research.navigation_failures', value: evaluation.navigationFailureCount, attributes },
    { name: 'dsh.research.source_files', value: evaluation.collection.filesRead, attributes },
    { name: 'dsh.research.source_bytes', value: evaluation.collection.sourceBytesRead, attributes },
    { name: 'dsh.research.duration_ms', value: evaluation.collection.durationMs, attributes },
    { name: 'dsh.research.cache_hit', value: evaluation.collection.cacheHit ? 1 : 0, attributes },
  ]
}

/**
 * Build median, p95, and MAD thresholds after the agreed 30-run sample floor.
 * @param samples - comparable compiler collection facts.
 * @returns undefined before 30 samples, otherwise a deterministic baseline.
 */
export function researchEfficiencyBaseline(
  samples: readonly VerifiedEvidenceLedger['collection'][],
): ResearchEfficiencyBaseline | undefined {
  if (samples.length < 30) return undefined
  return {
    sampleCount: samples.length,
    durationMs: efficiencyAxis(samples.map(sample => sample.durationMs)),
    sourceBytesRead: efficiencyAxis(samples.map(sample => sample.sourceBytesRead)),
    filesRead: efficiencyAxis(samples.map(sample => sample.filesRead)),
  }
}

function efficiencyAxis(values: readonly number[]): ResearchEfficiencyAxis {
  const ordered = [...values].sort((left, right) => left - right)
  const center = median(ordered)
  const deviations = ordered.map(value => Math.abs(value - center)).sort((left, right) => left - right)
  const mad = median(deviations)
  const p95 = requiredNumber(ordered, Math.ceil(ordered.length * 0.95) - 1)
  return { median: center, p95, mad, warnAbove: p95 + 3 * mad }
}

function median(ordered: readonly number[]): number {
  const middle = Math.floor(ordered.length / 2)
  return ordered.length % 2 === 0
    ? (requiredNumber(ordered, middle - 1) + requiredNumber(ordered, middle)) / 2
    : requiredNumber(ordered, middle)
}

function requiredNumber(values: readonly number[], index: number): number {
  const value = values[index]
  if (value === undefined) throw new Error('research efficiency samples must not be empty')
  return value
}

const evaluationSchema = z.object({
  reportHash: z.string(),
  reportFamily: z.enum(['technical-c4/v1', 'zj-draft/v1']),
  compilerVersion: z.literal('research/v1'),
  healthy: z.boolean(),
  correctness: z.object({
    revisionPinned: z.boolean(),
    provenanceComplete: z.boolean(),
    criticalClaimsEvidence: z.boolean(),
    scoringAxesSeparated: z.boolean(),
    publishExactlyOnce: z.boolean(),
    receiptConsistent: z.boolean(),
  }),
  evidenceCount: z.number().int().nonnegative(),
  unknownCount: z.number().int().nonnegative(),
  navigationFailureCount: z.number().int().nonnegative(),
  collection: z.object({
    filesRead: z.number().int().nonnegative(),
    sourceBytesRead: z.number().int().nonnegative(),
    durationMs: z.number().int().nonnegative(),
    cacheHit: z.boolean(),
  }),
})

/** Pure session projection definition for research health. */
export const researchHealthProjectionDefinition: ProjectionDefinition<'researchHealth', ResearchHealthProjection> = {
  key: 'researchHealth',
  schema: z.object({
    prepareAttempts: z.number().int().nonnegative(),
    invalidPrepareAttempts: z.number().int().nonnegative(),
    publishCount: z.number().int().nonnegative(),
    latestReceipt: z.object({ reportHash: z.string(), markdownPath: z.string(), htmlPath: z.string() }).nullable(),
    modelUsage: z.object({
      inputTokens: z.number().int().nonnegative(),
      outputTokens: z.number().int().nonnegative(),
      cacheReadTokens: z.number().int().nonnegative(),
      cacheWriteTokens: z.number().int().nonnegative(),
      reasoningTokens: z.number().int().nonnegative(),
    }),
    latest: evaluationSchema.nullable(),
  }),
  init: () => ({
    prepareAttempts: 0,
    invalidPrepareAttempts: 0,
    publishCount: 0,
    latestReceipt: null,
    modelUsage: emptyModelUsage(),
    latest: null,
  }),
  apply(state, event) {
    if (event.type === 'assistant/message' && event.data.usage !== undefined)
      return { ...state, modelUsage: addModelUsage(state.modelUsage, event.data.usage) }
    if (event.type === 'research/report-prepared')
      return {
        ...state,
        prepareAttempts: state.prepareAttempts + 1,
        invalidPrepareAttempts: state.invalidPrepareAttempts + (event.data.status === 'invalid' ? 1 : 0),
      }
    if (event.type === 'research/report-published') return { ...state, publishCount: state.publishCount + 1, latestReceipt: event.data }
    if (event.type === 'research/evaluation-completed') return { ...state, latest: event.data }
    return state
  },
  view: state => state,
  stateVersion: 0,
}

function emptyModelUsage(): ResearchModelUsage {
  return { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0 }
}

function addModelUsage(
  current: ResearchModelUsage,
  usage: {
    readonly inputTokens: number
    readonly outputTokens: number
    readonly cacheReadTokens?: number
    readonly cacheWriteTokens?: number
    readonly reasoningTokens?: number
  },
): ResearchModelUsage {
  return {
    inputTokens: current.inputTokens + usage.inputTokens,
    outputTokens: current.outputTokens + usage.outputTokens,
    cacheReadTokens: current.cacheReadTokens + (usage.cacheReadTokens ?? 0),
    cacheWriteTokens: current.cacheWriteTokens + (usage.cacheWriteTokens ?? 0),
    reasoningTokens: current.reasoningTokens + (usage.reasoningTokens ?? 0),
  }
}
